### ISSUE TITLE
Lifetime is wrong about &IdbVersionChangeEvent.

### ISSUE THREAD

**Issue by Mng12345** [Alorel/rust-indexed-db#10]
The cargo check's result is ok if i written the type of evt in the callback.
![image](https://user-images.githubusercontent.com/21278900/172977470-3b80cb49-070a-42e6-b662-121728d34f61.png)
But if i am not writting the type of evt and let it infered by the compiler, the cargo check complains me...
![image](https://user-images.githubusercontent.com/21278900/172977676-1bf9c462-d7ee-463a-9444-48336225ed8f.png)
Is it a problem of the rust compiler?

**Comment by Alorel** [comment]
It's a quirk with the rust compiler - [this](https://www.reddit.com/r/rust/comments/ntqu68/implementation_of_fnonce_is_not_general_enough/) is probably the clearest explanation. I'll close this since it's not really a library problem
