### ISSUE TITLE
`IdbVersionChangeEvent` should expose the current `IdbTransaction`

### ISSUE THREAD

**Issue by zecakeh** [Alorel/rust-indexed-db#20]
This event is fired during a transaction with mode `versionchange`, which should be available in `event.target.transaction`.

Although accessing the `IdbDatabase` allows us to create/delete object stores and set their indexes, it doesn't allow to access current stores. We need to access them via the `IdbTransaction`.

It would allow to change the indexes of the existing object stores, and to fix data in the stores or even migrate data from one store to the other.

**Comment by kurtbuilds** [comment]
I created a PR that exposes this API:

https://github.com/Alorel/rust-indexed-db/pull/26

**Comment by Alorel** [comment]
And it's released :slightly_smiling_face:

**Comment by kurtbuilds** [comment]
Amazing turn around time! Thank you
