### ISSUE TITLE
Should `OpenDbRequest::set_on_upgrade_needed` take a callback that returns a future?

### ISSUE THREAD

**Issue by zecakeh** [Alorel/rust-indexed-db#30]
In the callback we might need to `await` a transaction to make sure everything happens in the correct order.

For example porting the example of the ["Structuring the database" section of MDN's guide](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB#structuring_the_database) is currently not possible.

They recommend to wait for the `createObjectStore` transaction to be completed before adding data in it. In Rust code that requires turning the transaction into a future.

**Comment by Alorel** [comment]
This issue has been included in [v0.6.0](https://github.com/Alorel/rust-indexed-db/releases/tag/v0.6.0) :tada:

\- Your friendly neighbourhood [:robot: semantic release bot](https://github.com/alorel-actions/semantic-release-lite)
