### ISSUE TITLE
Remove UUID "wasm-bindgen" feature

### ISSUE THREAD

**Issue by TiemenSch** [Alorel/rust-indexed-db#35]
The UUID crate has changed it's feature flags and the `wasm-bindgen` flag has been removed since 1.7.0 or so (currently 1.8.0). 
The wasm-bindgen dependency itself is also included under  the `js ` flag.

**Comment by ptdecker** [comment]
revision: UUID currently 1.9.1

**Comment by Alorel** [comment]
Fixed with [0.4.2](https://github.com/Alorel/rust-indexed-db/releases/tag/v0.4.2), thanks!
