### ISSUE TITLE
How to get an index in a transaction

### ISSUE THREAD

**Issue by rklaehn** [Alorel/rust-indexed-db#4]
Hi,

first of all, thanks for this nice crate.

I want to work with indexes, and I wonder how I get an index in a transaction. Did I miss something, or is that not yet implemented? Basically this: https://developer.mozilla.org/en-US/docs/Web/API/IDBObjectStore/index

I can give it a try if this is indeed missing.

**Comment by Alorel** [comment]
Oops, it looks like I forgot to add that one in 😅 I'll try to get it implemented in the next few days

**Comment by Alorel** [comment]
It should now be available with [v0.2.1](https://github.com/Alorel/rust-indexed-db/releases/tag/0.2.1)

**Comment by rklaehn** [comment]
Thanks a lot! :heart:
