### ISSUE TITLE
Sample code produces error

### ISSUE THREAD

**Issue by dougalg** [Alorel/rust-indexed-db#6]
Hi, thanks for the library! I am trying to get a basic string-storage working as a first step, but ran into a problem while following the sample code in the lib.rs file. When attempting to use the exact code from the sample, it produces an error. I am using rustc `v1.24.3`.

```rust
db_req.set_on_upgrade_needed(Some(|evt: IdbVersionChangeEvent| -> Result<(), JsValue> {
	// Check if the object store exists; create it if it doesn't
	if let None = evt.db().object_store_names().find(|n| n == "my_store") {
		evt.db().create_object_store("my_store")?;
	}
	Ok(())
}));
```

```
type mismatch in closure arguments
expected signature of `for<'r> fn(&'r indexed_db_futures::IdbVersionChangeEvent) -> _`rustcE0631
indexeddb.rs(9, 36): found signature of `fn(indexed_db_futures::IdbVersionChangeEvent) -> _`
```

Do you have any suggestions? Thanks a lot!

**Comment by Alorel** [comment]
Hey, thanks for bringing this up - I missed an `&` in the example code; it should be

```rust
     // evt is passed by reference
     db_req.set_on_upgrade_needed(Some(|evt: &IdbVersionChangeEvent| -> Result<(), JsValue> {
         // Check if the object store exists; create it if it doesn't
         if let None = evt.db().object_store_names().find(|n| n == "my_store") {
             evt.db().create_object_store("my_store")?;
         }
         Ok(())
     }));
```

I'll patch it up and push an update to docs.rs. Let me know if there are any more issues!

**Comment by dougalg** [comment]
Oh my gosh I was so focused on the lifetime that I didn't notice the pass-by-reference.

Thanks a lot!
