### ISSUE TITLE
unable to retrieve Array value for JsCastRequestFuture when calling IdbObjectStore.get_all() 

### ISSUE THREAD

**Issue by MbBrainz** [Alorel/rust-indexed-db#9]
in trying to retrieve all the keys and values from my indexeddb, however, i have no idea how to get the Array type from the [`JsCastRequestFuture<Array>`](https://github.com/Alorel/rust-indexed-db/blob/495c206c41431cf43dfbeb63d448c7bdd3927a1c/src/request/futures/jscast_request_future.rs#L16) return type of

[`idbObjectStore.get_all()`](https://github.com/Alorel/rust-indexed-db/blob/495c206c41431cf43dfbeb63d448c7bdd3927a1c/src/idb_query_source.rs#L33)

Could you please contact me?

**Comment by Alorel** [comment]
https://rust-lang.github.io/async-book/

**Comment by MbBrainz** [comment]
I've got a working implementation of getting and setting values to the db. The asynchronous part is not where I get lost. The JsCastRequestFuture seems to work differently than the dbRequestFutures, which I managed to use successfully. Could you give a small example where you unpack a JsCastRequestFuture<Array> into a Array?

**Comment by Alorel** [comment]
It works exactly as described in the [docs](https://docs.rs/indexed_db_futures/0.2.3/indexed_db_futures/request/struct.JsCastRequestFuture.html) though and is the same kind of Future described in the async book.

```rust
    async fn reqfuture() {
        let db = {
            let mut req = IdbDatabase::open("db").unwrap();
            req.set_on_upgrade_needed(Some(move |evt: &IdbVersionChangeEvent| {
                evt.db().create_object_store("store")?;
                Ok(())
            }));
            req.into_future().await.unwrap()
        };

        insert_data(&db).await;

        let js_array = get_data(&db).await;
        let first = js_array.at(0).as_string().unwrap();
        let second = js_array.at(1).as_string().unwrap();

        assert_eq!(&first, "v1");
        assert_eq!(&second, "v2");
    }

    async fn get_data(db: &IdbDatabase) -> js_sys::Array {
        let tx = db.transaction_on_one("store").unwrap();

        let result = tx.object_store("store")
            .unwrap()
            .get_all()
            .unwrap()
            .await
            .unwrap();
        
        tx.await.into_result().unwrap();
        result
    }

    async fn insert_data(db: &IdbDatabase) {
        let tx = db
            .transaction_on_one_with_mode("store", IdbTransactionMode::Readwrite)
            .unwrap();
        let store = tx.object_store("store").unwrap();

        store.put_key_val(&JsValue::from("k1"), &JsValue::from("v1")).unwrap();
        store.put_key_val(&JsValue::from("k2"), &JsValue::from("v2")).unwrap();

        tx.await.into_result().unwrap();
    }
```

**Comment by MbBrainz** [comment]
Thank you for the example, it helped me clarify what i mean. There one distinct difference with the results from a `OptionalJsValueFuture`, which is returned from single object retrieval (e.g. `IdbObjectStore.get_owned(key)`) and the `JsCastRequestFuture<Array>`, that is returned by `IdbObjectStore.get_all()`, that caused my confusion. 

The type of the object which you get from OptionalJsValueFuture.await.unwrap().unwrap() is a JsValue, while the object returned from `JsCastRequestFuture<Array>.await.unwrap()` is unknown and has to be casted, using .into(), or in your example by the return type of the function. This was confusing to me, because of the `<Array>` part. Ive got it working now.

parts of my working code with get_all():
```rust
    pub async fn load_to_mem_storage(&mut self) {
        let store_name = "my_store";

        let tx = self.db.transaction_on_one_with_mode(store_name, IdbTransactionMode::Readonly).unwrap();
        let store = tx.object_store(store_name).unwrap();
        
        let data = store.get_all_keys().unwrap();
        let arraydata: Array = data.await.unwrap().into();
        ...
  }

```

part of my code with get_owned(key):
```rust 
    pub async fn get_item(&self, key: &[u8]) -> Vec<u8> {
        let tx = self.db.transaction_on_one("my_store").unwrap();
        let store = tx.object_store("my_store").unwrap();
        let async_res = store.get_owned(Uint8Array::from(key)).unwrap();
        let res = async_res.await.unwrap().unwrap();
        let bytes = Uint8Array::new(&res).to_vec();
        return bytes;
    }

```
